NEST_PATH: /p/software/default/stages/2025/software/nest-simulator/3.8-gpsmpi-2024a/

MPIRUN: srun
MPI_MODULES: module load Stages/2025 Python/3.11.3 GCC ParaStationMPI CMake Boost GSL SciPy-Stack Autotools git PyYAML nest-simulator/3.8
